<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ServiceChildModel;

class ServiceChildSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $service_child = [
            ['service_child_name'=>'CRM','service_child_description'=>'Customer Relation Management. This is a database technology for managing all your companys relationships and interactions with customers and potential customers. The goal is simple: Improve business relationships. A CRM system helps companies stay connected to customers, streamline processes, and improve profitability.Running a business without CRM can cost you real money. More administration means less time for everything else. An active sales team can generate a flood of data. Reps are out on the road talking to customers, meeting prospects, and finding out valuable informationbut all too often this information gets stored in handwritten notes, laptops, or inside the heads of your sales people.','service_child_parentID'=>1,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/sda/portfolio-crm-1.jpg"]'],
            ['service_child_name'=>'Mobile Arg Dev','service_child_description'=>'Mobile application development is the process to making software for smartphones and digital assistants, most commonly for Android and iOS. The software can be preinstalled on the device, downloaded from a mobile app store or accessed through a mobile web browser. The programming and markup languages used for this kind of software development include Java, Swift, C# and HTML5.Mobile app development is rapidly growing. From retail, telecommunications and e- commerce to insurance, healthcare and government, organizations across industries must meet user expectations for real-time, convenient ways to conduct transactions and access information. Today, mobile devices—and the mobile applications that unlock their value—are the most popular way for people and businesses to connect to the internet. To stay relevant, responsive and successful, organizations need to develop the mobile applications that their customers, partners and employees demand.','service_child_parentID'=>1,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/sda/portfolio-mda-1.jpg"]'],
            ['service_child_name'=>'Web Dev','service_child_description'=>'Web development refers in general to the tasks associated with developing websites for hosting via intranet or internet. The web development process includes web design, web content development, client- side/server-side scripting and network security configuration, among other tasks. Web development is the process of building, programming, and maintaining websites and web applications. Website developers use various programming languages, like HTML, CSS, and JavaScript, to develop websites and web applications. Web development is a critical element in any digital marketing campaign because your website lies at the heart of all your online marketing. Your paid ads, social media, and email campaigns ultimately lead users back to your site.','service_child_parentID'=>1,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/sda/portfolio-wd-1.jpg"]'],
            ['service_child_name'=>'Social Media Mgt','service_child_description'=>'Social media management is the process of managing your online presence on social media platforms. Social media managers will use their experience, plus tools and services to create and publish content, interact with users, and analyze performance.Social media management is the process of creating, publishing, and analyzing content you post on social media platforms like Facebook, Instagram, and Twitter, as well as engaging with users on those platforms. You can streamline social media management tasks with free and paid tools, as well as professional social media management services. Social media offers your company a tremendous opportunity to grow your brand and your business. Its a challenge, though, for many organizations, especially small-to-midsized businesses (SMBs), to set aside the time and resources for social media management.','service_child_parentID'=>2,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/ivp/portfolio-smm-1.jpg"]'],
            ['service_child_name'=>'Social Media Adv','service_child_description'=>'Social media advertising is a type of digital marketing that utilizes social networks such as Facebook, Twitter, and Instagram to deliver paid ads to your target audience. Social media ads are a quick and effective way to connect with your consumers and boost your marketing campaigns. By leveraging various data sources, advertisers are able to hyper-target their audiences and deliver personalized content based on demographics and user behavior. When an audience is introduced to a brand on social media, advertisers may see more interactions and conversions. Social media ads are also cost-effective, offering the potential for high rates of return. Social advertising is a must if you want to quickly reach new target markets. More and more companies — including the worlds top- performing brands — utilize social media ads to grow their companies and reach out to new consumers. To keep up with the competition, its important to learn how these ads work and how they can benefit your company.','service_child_parentID'=>2,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/ivp/portfolio-sma-1.jpg"]'],
            ['service_child_name'=>'SEO','service_child_description'=>'SEO stands for “search engine optimization.” In simple terms, it means the process of improving your site to increase its visibility when people search for products or services related to your business in Google, Bing, and other search engines. The better visibility your pages have in search results, the more likely you are to garner attention and attract prospective and existing customers to your business. SEO is a fundamental part of digital marketing because people conduct trillions of searches every year, often with commercial intent to find information about products and services. Search is often the primary source of digital traffic for brands and complements other marketing channels. Greater visibility and ranking higher in search results than your competition can have a material impact on your bottom line.','service_child_parentID'=>2,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/ivp/portfolio-seo-1.jpg"]'],
            ['service_child_name'=>'Printed Mktg. Materials','service_child_description'=>'are intended as any kind of branded element and material used to promote a brand, product or service.The most common form of marketing materials is “literature”, basically any type of printed pieces with the job of promoting and presenting a product, used within a marketing strategy. They could be, for example: business cards, letterhead, flyers, brochures, presentation folders, thank you cards, postcards etc. Printed marketing materials are the foundation of any impactful marketing campaign. Designed to pique the interest of the media and your reading audience, they are a great tool to give away, and are an invaluable part of any book signing event','service_child_parentID'=>3,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/cm/portfolio-pmm-1.jpg"]'],
            ['service_child_name'=>'Print & Digital Billboard','service_child_description'=>'Engage with Customers on a grand scale. Increase brand recognition through creative and engaging visuals. Use billboards designed by leading artists to engage, impress, and inspire people. Our creation process enables top tier flexibility where you can contribute ideas and feedbacks in order to ensure the best designs','service_child_parentID'=>3,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/cm/portfolio-pdb-1.jpeg"]'],
            ['service_child_name'=>'Magazine & Newspaper Mktg','service_child_description'=>' Print advertising is a widely used form of advertising. These advertisements appear in newspapers or magazines and are sometimes included as brochures or fliers. Anything written  in the print media to grab the attention of the specific target audience comes under the purview of print advertising.','service_child_parentID'=>3,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/cm/portfolio-mnm-1.jpeg"]'],
            ['service_child_name'=>'Lead Mining','service_child_description'=>'Involve purchasing lists of names and sales representatives cold calling people at home, but modern advances in technology have made it possible for us to now generate leads based on specific criteria and information. Companies collect information about potential buyers and  then tailor marketing methods and sales pitches  to the prospects needs. This is largely done through digital channels, using inbound marketing techniques alongside some of the former outbound marketing methods. Successful lead generation can make the sales cycle more efficient, and lead to greater success rates in new customer acquisition.','service_child_parentID'=>4,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/ete/portfolio-lm-1.jpg"]'],
            ['service_child_name'=>'Logo Design','service_child_description'=>'is the process of designing a logo. Logos serve to represent a given organization or company through a visual image that can be easily understood and recognized. A logo generally involves symbols, stylized text or both. Logos are often created by a graphic artist in consultation with a company and marketing experts.','service_child_parentID'=>4,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/ete/portfolio-ld-1.jpg"]'],
            ['service_child_name'=>'Slogans & Tagline','service_child_description'=>'Slogans impart the companys mission, while taglines call to mind an image of the brand. A slogan is more advertising focused, and a tagline is more public relations focused, meaning slogans are used to sell an item and taglines raise awareness about the overall brand. Unlike slogans, taglines dont tell customers what your company does. Instead, taglines narrow in on a certain aspect of a company.','service_child_parentID'=>4,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/ete/portfolio-st-1.jpeg"]'],
            ['service_child_name'=>'Scheduling & Travel Coordination','service_child_description'=>'Handle your travel arrangements and schedule — making sure that you dont have to worry about minute details of your next conference or event. They can also follow up on your meetings, get in touch with your vendors, partners, and suppliers for a smooth operational process.','service_child_parentID'=>5,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/va/portfolio-stc-1.jpeg"]'],
            ['service_child_name'=>'Remote Office Management','service_child_description'=>'Handle your travel arrangements and schedule — making sure that you dont have to worry about minute details of your next conference or event. They can also follow up on your meetings, get in touch with your vendors, partners, and suppliers for a smooth operational process.','service_child_parentID'=>5,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/va/portfolio-rom-1.jpeg"]'],
            ['service_child_name'=>'Data Entry','service_child_description'=>'A Data Entry Clerk is responsible for transferring data from paper formats into computer files or database systems. Their transfer of data happens manually or using scanners. They type in customers information and create spreadsheets, verifying them against source documents at different stages during the process','service_child_parentID'=>5,'service_child_status'=>1,'service_child_img'=>'["img_1"=>"/img/portfolio/va/portfolio-de-1.jpg"]'],
        ];
        foreach($service_child as $value){
            ServiceChildModel::create($value);
        }
    }
}
